apiVersion: storage.loft.sh/v1
kind: AccessKey
metadata:
  name: admin-user-72tnz
spec:
  displayName: demo-env-admin-access-key
  key: "${accessKey}"
  type: User
  user: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: vcluster-platform-provider-headers
  namespace: p-auth-core
stringData:
  headers: |
    Authorization: Bearer ${accessKey}
---
apiVersion: v1
kind: Secret
metadata:
  name: github-app-secret
  namespace: p-auth-core
  labels:
    loft.sh/project-secret-name: loft-demo-org-cred
data:
---
