kind: VirtualClusterInstance
apiVersion: management.loft.sh/v1
metadata:
  name: vcluster-deployed-with-flux
  namespace: p-auth-core
spec:
  displayName: vCluster Deployed with Flux
  owner:
    team: loft-admins
  template:
    metadata: {}
    instanceTemplate:
      metadata: {}
    access:
      defaultClusterRole: view
      rules:
        - teams:
            - loft-admins
          clusterRole: cluster-admin
    pro:
      enabled: true
    helmRelease:
      chart:
        name: vcluster
        repo: https://loft-demos.github.io/vcluster-charts
        version: 0.23.0
      values: |
        sync:
          toHost:
            ingresses:
              enabled: true

        exportKubeConfig:
          context: loft
          server: https://vcluster-deployed-with-flux.loft-auth-core-v-vcluster-deployed-with-flux:443
          secret:
            name: vcluster-platform-kubeconfig

        controlPlane:
          coredns:
            enabled: true
            embedded: true
          backingStore:
            etcd:
              embedded:
                enabled: true
          statefulSet:
            image:
              repository: "loft-demos/vcluster-pro"
              tag: "0.23.0-k8s.v1.32.1"
    accessPoint:
      ingress: {}
    spaceTemplate:
      metadata: {}
      objects: |-
        ---
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: apps
        spec:
          interval: 1h
          retryInterval: 3m
          timeout: 5m
          prune: true
          wait: true
          dependsOn:
            - name: vcluster-instance
              namespace: p-auth-core
          path: ./vcluster-gitops/argocd/flux/flux-deploy-apps
          sourceRef:
            kind: GitRepository
            name: {REPLACE_REPO_NAME}
            namespace: p-auth-core
          patches:
            - target:
                kind: HelmRepository
              patch: |
                - op: add
                  path: /metadata/namespace
                  value:
                    p-auth-core
            - target:
                kind: HelmRelease
              patch: |
                - op: add
                  path: /metadata/namespace
                  value:
                    p-auth-core
                - op: add
                  path: /spec/kubeConfig
                  value:
                    secretRef:
                      name: vcp-vcluster-deployed-with-flux-flux-kubeconfig
                - op: add
                  path: /spec/values
                  value:
                    ui:
                      message: "deployed to vcluster-deployed-with-flux test-11"
                - op: add
                  path: /spec/values/ingress
                  value:
                    enabled: true
                    hosts:
                      - host: podinfo-vcluster-deployed-with-flux-{REPLACE_VCLUSTER_NAME}.us.demo.dev
                        paths:
                          - path: /
                            pathType: ImplementationSpecific
  clusterRef:
    cluster: loft-cluster
  access:
    - name: instance-access
      verbs:
        - create
        - use
        - get
      subresources:
        - logs
        - kubeconfig
      teams:
        - auth-core
        - loft-admins
  networkPeer: true
