apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: vcluster-flux-demo
  namespace: p-vcluster-flux-demo
spec:
  interval: 5m0s
  url: 'http://forgejo-http.forgejo.svc.cluster.local:3000/vcluster-demos/vcp-gitops.git'
  ref:
    branch: main
