controlPlane:
  backingStore:
    etcd:
      embedded:
        enabled: true
  coredns:
    embedded: true
  distro:
    k8s:
      image:
        tag: v1.33.4
  standalone:
    enabled: true
    joinNode:
      enabled: true

privateNodes:
  enabled: true
  vpn:
    enabled: true
    nodeToNode:
      enabled: true
