apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-runner-config
  namespace: forgejo
data:
  config.yaml: |
    log:
      level: info
    runner:
      file: /data/.runner
      capacity: 1
      labels:
        - docker:docker://node:20-bookworm
        - ubuntu-latest:docker://node:20-bookworm
        - ubuntu-22.04:docker://node:20-bookworm
        - ubuntu-20.04:docker://node:18-bullseye
      envs:
        DOCKER_HOST: unix:///var/run/docker.sock
      timeout: 3h
      insecure: false
      fetch_timeout: 5s
      fetch_interval: 2s
    cache:
      enabled: true
      dir: /data/cache
    container:
      network: bridge
      privileged: false
      valid_volumes: []
      docker_host: unix:///var/run/docker.sock
      options: >-
        --volume /etc/docker/certs.d:/etc/docker/certs.d:ro
      force_pull: false
    host:
      workdir_parent: /data/workdir
