apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auto-snapshots-manifests
  namespace: argocd
spec:
  source:
    path: vcluster-use-cases/auto-snapshots/manifests/overlays/local-contained
