apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcp-oidc-clients
  namespace: argocd
  labels:
    use-case.demos.vcluster.com: continuous-promotion
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: vcluster-platform
  project: default
  source:
    repoURL: '{REPLACE_GIT_BASE_URL}/{REPLACE_ORG_NAME}/{REPLACE_REPO_NAME}'
    targetRevision: '{REPLACE_GIT_TARGET_REVISION}'
    path: vcluster-use-cases/continuous-promotion/manifests/vcp-oidc-clients
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 3m
