apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kargo-github-webhook-secret
  namespace: kargo-system-resources
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vcp-demo-store
  target:
    name: kargo-github-webhook-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          kargo.akuity.io/cred-type: generic
      data:
        secret: "{{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        key: pr-github-receiver-token/token
