apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  context: |
    argocdUrl: https://argocd-{REPLACE_VCLUSTER_NAME}.us.demo.dev
  # Define the webhook service for vCluster Platform
  service.webhook.vcluster-platform: |
    url: https://{REPLACE_VCLUSTER_NAME}.us.demo.dev
    headers:
    - name: Authorization
      value: "Bearer $accessKey"
    - name: User-Agent
      value: "vcluster-wakeup"
  # Template for waking up the vCluster via vCluster Platform API
  template.wakeup-vcluster: |
    webhook:
      vcluster-platform:
        method: POST
        path: /kubernetes/project/{{ index .app.metadata.labels "vclusterProjectId" }}/virtualcluster/{{ index .app.metadata.labels "vclusterName" }}
  # Trigger wake-up when app becomes OutOfSync
  trigger.wakeup-vcluster: |
    - description: "Wake vCluster when app is OutOfSync"
      when: app.status.sync.status == 'OutOfSync'
      send: [wakeup-vcluster]
