apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vcluster-wakeup-proxy
  namespace: progressive-delivery
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vcp-demo-store
  target:
    name: vcluster-wakeup-proxy
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          kargo.akuity.io/cred-type: generic
      data:
        accessKey: "{{ .accessKey }}"
  data:
    - secretKey: accessKey
      remoteRef:
        key: demo-admin-access-key/accessKey
