apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pr-vcluster-external-argocd
  namespace: argocd
spec:
  generators:
    - pullRequest:
        github:
          appSecretName: loft-demo-org-cred
          labels:
            - create-pr-vcluster-external-argocd
          owner: vcluster-demos
          repo: vcp-gitops
        requeueAfterSeconds: 30
        template:
          metadata: {}
          spec:
            destination: {}
            project: ''
  template:
    metadata:
      name: vcp-gitops-pr-{{number}}-vcluster
    spec:
      destination:
        name: in-cluster
        namespace: p-auth-core
      info:
        - name: PR vCluster Argo CD URL
          value: https://argocd-vcp-gitops.vcp.local
        - name: Pull Request
          value: 'https://forgejo.vcp.local/vcluster-demos/vcp-gitops/pull/{{number}}'
      project: loft-auth-core
      source:
        kustomize:
          namePrefix: vcp-gitops-pr-{{number}}-
          patches:
            - patch: |-
                - op: add
                  path: /metadata/labels/vclusterProjectId
                  value: auth-core
                - op: add
                  path: /metadata/labels/vclusterName
                  value: vcp-gitops-pr-{{number}}-vcluster
                - op: add
                  path: /metadata/labels/repo
                  value: vcp-gitops
                - op: add
                  path: /metadata/labels/prLabel
                  value: 'create-pr-vcluster-external-argocd'
                - op: add
                  path: /metadata/labels/prNumber
                  value: '{{number}}'
                - op: add
                  path: /metadata/labels/targetRevision
                  value: '{{head_sha}}'
                - op: add
                  path: /metadata/labels/headShortSha
                  value: '{{head_short_sha}}'
                - op: add
                  path: /metadata/labels/headBranch
                  value: '{{branch}}'
              target:
                kind: VirtualClusterInstance
                name: vcluster
        path: vcluster-use-cases/argocd-vcluster-pull-request-environments/kustomize
        repoURL: 'http://forgejo-http.forgejo.svc.cluster.local:3000/vcluster-demos/vcp-gitops.git'
        targetRevision: '{{branch}}'
      syncPolicy:
        automated:
          selfHeal: true
