apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pr-vcluster-internal-argocd
  namespace: argocd
spec:
  generators:
    - pullRequest:
        github:
          appSecretName: loft-demo-org-cred
          labels:
            - create-prvcluster
          owner: vcluster-demos
          repo: vcp-gitops
        requeueAfterSeconds: 30
        template:
          metadata: {}
          spec:
            destination: {}
            project: ''
  template:
    metadata:
      name: vcp-gitops-pr-{{number}}
    spec:
      destination:
        name: in-cluster
        namespace: p-api-framework
      info:
        - name: PRvCluster Argo CD URL
          value: https://argocd-vcp-gitops-pr-{{number}}.vcp.local
        - name: Pull Request
          value: 'https://forgejo.vcp.local/vcluster-demos/vcp-gitops/pull/{{number}}'
      project: default
      source:
        kustomize:
          namePrefix: vcp-gitops-pr-{{number}}-
          patches:
            - patch: |-
                - op: replace
                  path: /spec/prNumber
                  value: '{{number}}'
              target:
                kind: PullRequestEnvironment
                name: vcluster
        path: vcluster-use-cases/argocd-vcluster-pull-request-environments/internal/kustomize
        repoURL: 'http://forgejo-http.forgejo.svc.cluster.local:3000/vcluster-demos/vcp-gitops.git'
        targetRevision: '{{head_sha}}'
      syncPolicy:
        automated:
          selfHeal: true
