apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: vcp-gitops
  namespace: p-auth-core
spec:
  interval: 5m0s
  url: 'http://forgejo-http.forgejo.svc.cluster.local:3000/vcluster-demos/vcp-gitops.git'
  ref:
    branch: main
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: github-dispatch
  namespace: p-auth-core
spec:
  type: githubdispatch
  address: 'https://forgejo.vcp.local/vcluster-demos/vcp-gitops'
  secretRef:
    name: loft-demo-org-cred
---
