---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: podinfo
  namespace: loft-auth-core-v-auth-core-dev
spec:
  interval: 12h
  type: oci
  url: oci://ghcr.io/stefanprodan/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: loft-auth-core-v-auth-core-dev
spec:
  targetNamespace: podinfo
  storageNamespace: podinfo
  releaseName: podinfo
  kubeConfig:
    secretRef:
      name: vcluster-flux-kubeconfig
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
  interval: 50m
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml
  values:
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: podinfo-auth-core-dev-{REPLACE_VCLUSTER_NAME}.us.demo.dev
          paths:
            - path: /
              pathType: ImplementationSpecific
