apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/

patches:
  - path: patch-k8s-version.yaml
    target:
      kind: VirtualClusterTemplate
      version: v1
      labelSelector: patchType=non-versioned
patchesJson6902:
  - target:
      group: management.loft.sh
      version: v1
      kind: VirtualClusterTemplate
      name: default-template
    path: patch-k8s-versioned.json
