apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../auto-snapshots-vcluster-template.yaml
  - ../../auto-snapshots-vcluster.yaml
  - minio/namespace.yaml
  - minio/pvc.yaml
  - minio/deployment.yaml
  - minio/service.yaml
  - minio/ingress.yaml
  - minio/bucket-init-job.yaml
patches:
  - path: patch-snapshot-storage.yaml
