apiVersion: v1
kind: Secret
metadata:
  name: kargo-auth-values
  namespace: p-vcluster-flux-demo
type: Opaque
stringData:
  values.yaml: |
    api:
      adminAccount:
        enabled: true
        passwordHash: "{REPLACE_KARGO_ADMIN_PASSWORD_HASH}"
        tokenSigningKey: "{REPLACE_KARGO_TOKEN_SIGNING_KEY}"
