apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kargo-auth-values
  namespace: p-vcluster-flux-demo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vcp-demo-store
  target:
    name: kargo-auth-values
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          reconcile.fluxcd.io/watch: Enabled
      data:
        password: "{{ .password }}"
        values.yaml: |
          api:
            adminAccount:
              enabled: true
              passwordHash: "{{ .passwordHash }}"
              tokenSigningKey: "{{ .tokenSigningKey }}"
  data:
    - secretKey: passwordHash
      remoteRef:
        key: kargo-admin/passwordHash
    - secretKey: tokenSigningKey
      remoteRef:
        key: kargo-admin/tokenSigningKey
    - secretKey: password
      remoteRef:
        key: kargo-admin/password
