apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../shared-host-eso
patches:
  - target:
      kind: Ingress
      name: guestbook
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: guestbook-ppg-prod-{REPLACE_VCLUSTER_NAME}.{REPLACE_BASE_DOMAIN}
  - target:
      kind: Deployment
      name: guestbook
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args
        value:
          - --text=guestbook prod
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: DEMO_SHARED_MESSAGE
          valueFrom:
            secretKeyRef:
              name: guestbook-shared-config
              key: message
