apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: custom-resource-sync-manifests
  namespace: argocd
  labels:
    use-case.demos.vcluster.com: custom-resource-sync
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    repoURL: '{REPLACE_GIT_BASE_URL}/{REPLACE_ORG_NAME}/{REPLACE_REPO_NAME}'
    targetRevision: HEAD
    path: vcluster-use-cases/custom-resource-sync/manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 3m
