apiVersion: v1
kind: Secret
metadata:
  name: oidc-client-forgejo
  namespace: vcluster-platform
  labels:
    clientID: forgejo
    component: oidcServer
stringData:
  name: Forgejo
  clientID: forgejo
  clientSecret: "{REPLACE_FORGEJO_OIDC_SECRET}"
  redirectURIs: "http://forgejo.{REPLACE_BASE_DOMAIN}/user/oauth2/vcluster-platform/callback"
