apiVersion: v1
kind: Secret
metadata:
  name: cnpg-postgres-admin
  namespace: cnpg-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  username: postgres
  password: vcluster-demo-postgres
