apiVersion: v1
kind: Secret
metadata:
  name: postgres-database-connector
  namespace: vcluster-platform
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    loft.sh/display-name: "PostgreSQL DB Connector"
  labels:
    loft.sh/connector-type: "shared-database"
type: Opaque
stringData:
  endpoint: postgres-cluster-rw.cnpg-system.svc.cluster.local
  port: "5432"
  user: postgres
  password: '{REPLACE_DB_CONNECTOR_PASSWORD}'
  type: postgres
