apiVersion: v1
kind: Secret
metadata:
  name: postgres-cluster-superuser
  namespace: cnpg-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: '{REPLACE_DB_CONNECTOR_PASSWORD}'
