apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Ingress
      name: guestbook
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: guestbook-prod-{REPLACE_VCLUSTER_NAME}.{REPLACE_BASE_DOMAIN}
  - target:
      kind: Deployment
      name: guestbook
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args
        value:
          - --text=guestbook prod
