kind: App
apiVersion: management.loft.sh/v1
metadata:
  name: eso
spec:
  displayName: External Secrets Operator
  description: External Secrets Operator is a Kubernetes operator that integrates external secret management 
  recommendedApp:
    - cluster
  defaultNamespace: eso
  icon: https://artifacthub.io/image/f23fb631-4a3c-46c0-bda1-7a048cabf10d@2x
  config:
    chart:
      name: external-secrets
      version: 2.2.0
      repoURL: https://charts.external-secrets.io/
    values: '{{ .Values.appValues }}'
  parameters:
    - variable: appValues
      label: Helm Values
      description: The helm values to use to deploy this chart.
      type: multiline
      defaultValue: |-
        fullnameOverride: eso
        installCRDs: true
        webhook:
          create: false
        certController:
          create: false
        crds:
          conversion:
            enabled: false
  versions:
    - icon: https://artifacthub.io/image/f23fb631-4a3c-46c0-bda1-7a048cabf10d@2x
      defaultNamespace: eso
      config:
        chart:
          name: external-secrets
          version: 2.2.0
          repoURL: https://charts.external-secrets.io/
        values: '{{ .Values.appValues }}'
      parameters:
        - variable: appValues
          label: Helm Values
          description: The helm values to use to deploy this chart.
          type: multiline
          defaultValue: |-
            fullnameOverride: eso
            installCRDs: true
            webhook:
              create: false
            certController:
              create: false
            crds:
              conversion:
                enabled: false
      wait: true
      version: 2.2.0
  access:
    - verbs:
        - get
      users:
        - '*'
