apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-pre-prod-gate
  namespace: argocd
  labels:
    use-case.demos.vcluster.com: continuous-promotion
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: '{REPLACE_GIT_BASE_URL}/{REPLACE_ORG_NAME}/{REPLACE_REPO_NAME}'
    targetRevision: '{REPLACE_GIT_TARGET_REVISION}'
    path: vcluster-use-cases/continuous-promotion/manifests/pre-prod-gate
  destination:
    server: https://kubernetes.default.svc
    namespace: pre-prod-gate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
