apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-observability-cluster
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            tenantObservability: 'true'
  template:
    metadata:
      name: tenant-observability-apps
      labels:
        use-case.demos.vcluster.com: tenant-observability
    spec:
      destination:
        server: '{{server}}'
        namespace: argocd
      project: default
      source:
        repoURL: '{REPLACE_GIT_BASE_URL}/{REPLACE_ORG_NAME}/{REPLACE_REPO_NAME}'
        targetRevision: HEAD
        path: vcluster-use-cases/tenant-observability/apps
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - Replace=true
        retry:
          limit: 5
          backoff:
            duration: 20s
            factor: 2
            maxDuration: 3m
