# The Argo CD Application for shared wake-up plumbing for sleeping imported vCluster instances
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-sleep-wakeup-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    use-case.demos.vcluster.com: bootstrap
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: '{REPLACE_GIT_BASE_URL}/{REPLACE_ORG_NAME}/{REPLACE_REPO_NAME}'
    targetRevision: '{REPLACE_GIT_TARGET_REVISION}'
    path: vcluster-gitops/argocd/vcluster-sleep-wakeup/base
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
