apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-in-vcluster-applicationsets
  namespace: argocd
  labels:
    use-case.demos.vcluster.com: argocd-in-vcluster
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: argocd-in-vcluster
  source:
    repoURL: '{REPLACE_GIT_BASE_URL}/{REPLACE_ORG_NAME}/{REPLACE_REPO_NAME}'
    targetRevision: HEAD
    path: vcluster-use-cases/argocd-in-vcluster/applicationsets
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true    
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 1m
