apiVersion: v1
kind: Secret
metadata:
  name: argo-webhook-url
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  url: "https://argocd-{REPLACE_VCLUSTER_NAME}.{REPLACE_BASE_DOMAIN}/api/webhook"
