apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: guestbook
  namespace: pre-prod-gate
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  subscriptions:
    - image:
        repoURL: '{REPLACE_APP_IMAGE_REPOSITORY}'
        semverConstraint: ">=0.0.1"
        discoveryLimit: 5
        insecureSkipTLSVerify: true
        interval: 24h # relies on webhook for updates
