apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-gitops
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: vcluster-gitops/overlays/local-contained
    repoURL: 'http://forgejo-http.forgejo.svc.cluster.local:3000/vcluster-demos/vcp-gitops.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
