apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../gitrepository.yaml
  - ../../flux-notification-ingress.yaml
  - ../../generate-vcluster-kubeconfig.yaml
  - ../../flux-kustomization.yaml
patches:
  - path: patch-gitrepositories.yaml
  - path: patch-gitrepository-flux-demo.yaml
  - path: patch-github-dispatch.yaml
