apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: github-status
  namespace: p-auth-core
spec:
  type: github
  address: 'https://forgejo.vcp.local/vcluster-demos/vcp-gitops'
  secretRef:
    name: loft-demo-org-cred
---
