apiVersion: management.loft.sh/v1
kind: NodeProvider
metadata:
  name: pod-node-provider
spec:
  displayName: Pod Node Provider
  terraform:
    nodeTemplate:
      git:
        repository: 'http://forgejo-http.forgejo.svc.cluster.local:3000/{REPLACE_ORG_NAME}/vcluster-auto-nodes-pod.git'
        subPath: node
        credentials:
          secretName: forgejo-node-provider-cred
    nodeEnvironmentTemplate:
      infrastructure:
        git:
          repository: 'http://forgejo-http.forgejo.svc.cluster.local:3000/{REPLACE_ORG_NAME}/vcluster-auto-nodes-pod.git'
          subPath: environment/infrastructure
          credentials:
            secretName: forgejo-node-provider-cred
    nodeTypes:
      - name: a-small
        resources:
          cpu: "500m"
          memory: "256Mi"
          pods: "10"
        maxCapacity: 8
      - name: b-medium
        resources:
          cpu: "750m"
          memory: "512Mi"
          pods: "20"
        maxCapacity: 4
      - name: c-large
        resources:
          cpu: "1"
          memory: 1Gi
          pods: "30"
        maxCapacity: 2
