apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pr-vcluster-multi-k8s
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - k8sVersion: v1.33.3
                  k8sVersionDNSLabel: 1-33-3
                - k8sVersion: v1.32.7
                  k8sVersionDNSLabel: 1-32-7
          - pullRequest:
              gitea:
                owner: vcluster-demos
                repo: vcp-gitops
                api: "http://forgejo-http.forgejo.svc.cluster.local:3000"
                tokenRef:
                  secretName: loft-demo-org-cred
                  key: token
              requeueAfterSeconds: 30
              template:
                metadata: {}
                spec:
                  destination: {}
                  project: ''
  template:
    spec:
      info:
        - name: PR vCluster Argo CD URL
          value: https://argocd-vcp-gitops.vcp.local
        - name: Pull Request
          value: 'https://forgejo.vcp.local/vcluster-demos/vcp-gitops/pulls/{{number}}'
      source:
        repoURL: 'http://forgejo-http.forgejo.svc.cluster.local:3000/vcluster-demos/vcp-gitops.git'
