apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-pr-preview-manifests
  namespace: argocd
spec:
  source:
    path: vcluster-use-cases/argocd-vcluster-pull-request-environments/manifests/overlays/local-contained
