apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: {REPLACE_REPO_NAME}
  namespace: p-auth-core
spec:
  interval: 5m0s
  url: https://github.com/loft-demos/{REPLACE_REPO_NAME}.git
  ref:
    branch: main
