apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-kargo-progressive-delivery
  namespace: p-vcluster-flux-demo
spec:
  dependsOn:
    - name: flux-kargo-install
      namespace: p-vcluster-flux-demo
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: vcluster-flux-demo
    namespace: p-vcluster-flux-demo
  path: ./vcluster-use-cases/continuous-promotion/manifests/progressive-delivery
