apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-kargo-progressive-delivery-platform
  namespace: p-vcluster-flux-demo
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: vcluster-flux-demo-kargo
    namespace: p-vcluster-flux-demo
  path: ./vcluster-use-cases/continuous-promotion/manifests/progressive-delivery
  patches:
    - target:
        group: kargo.akuity.io
        version: v1alpha1
        kind: Project
        name: progressive-delivery
        namespace: progressive-delivery
      patch: |
        $patch: delete
        apiVersion: kargo.akuity.io/v1alpha1
        kind: Project
        metadata:
          name: progressive-delivery
          namespace: progressive-delivery
    - target:
        group: argoproj.io
        version: v1alpha1
        kind: AnalysisTemplate
        name: guestbook-health
        namespace: progressive-delivery
      patch: |
        $patch: delete
        apiVersion: argoproj.io/v1alpha1
        kind: AnalysisTemplate
        metadata:
          name: guestbook-health
          namespace: progressive-delivery
    - target:
        group: kargo.akuity.io
        version: v1alpha1
        kind: Warehouse
        name: guestbook
        namespace: progressive-delivery
      patch: |
        $patch: delete
        apiVersion: kargo.akuity.io/v1alpha1
        kind: Warehouse
        metadata:
          name: guestbook
          namespace: progressive-delivery
    - target:
        group: kargo.akuity.io
        version: v1alpha1
        kind: ProjectConfig
        name: progressive-delivery
        namespace: progressive-delivery
      patch: |
        $patch: delete
        apiVersion: kargo.akuity.io/v1alpha1
        kind: ProjectConfig
        metadata:
          name: progressive-delivery
          namespace: progressive-delivery
    - target:
        group: kargo.akuity.io
        version: v1alpha1
        kind: Stage
        name: dev
        namespace: progressive-delivery
      patch: |
        $patch: delete
        apiVersion: kargo.akuity.io/v1alpha1
        kind: Stage
        metadata:
          name: dev
          namespace: progressive-delivery
    - target:
        group: kargo.akuity.io
        version: v1alpha1
        kind: Stage
        name: staging
        namespace: progressive-delivery
      patch: |
        $patch: delete
        apiVersion: kargo.akuity.io/v1alpha1
        kind: Stage
        metadata:
          name: staging
          namespace: progressive-delivery
    - target:
        group: kargo.akuity.io
        version: v1alpha1
        kind: Stage
        name: prod
        namespace: progressive-delivery
      patch: |
        $patch: delete
        apiVersion: kargo.akuity.io/v1alpha1
        kind: Stage
        metadata:
          name: prod
          namespace: progressive-delivery
