apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-kargo-auth.yaml
  - flux-kargo-install.yaml
  - flux-kargo-cluster-secrets.yaml
  - flux-kargo-cluster-config.yaml
  - flux-kargo-pre-prod-gate-platform.yaml
  - flux-kargo-pre-prod-gate.yaml
  - flux-kargo-progressive-delivery-platform.yaml
  - flux-kargo-progressive-delivery.yaml
