apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kargo-auth-values-external-secret.yaml
  - flux-kargo-install.yaml
  - flux-kargo-pre-prod-gate.yaml
  - flux-kargo-progressive-delivery.yaml
