kind: VirtualClusterTemplate
apiVersion: management.loft.sh/v1
metadata:
  name: preview-template
spec:
  displayName: vCluster Preview Template
  template:
    metadata:
      labels:
        loft.sh/import-argocd: 'true'
      annotations:
        sleepmode.loft.sh/delete-after: '72000'
        loft.sh/require-ingress-authentication: 'true'
        sleepmode.loft.sh/sleep-after: '600'
        sleepmode.loft.sh/ignore-user-agents: 'argo*'
    objects: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: preview-hello-world-app
      ---
      apiVersion: v1
      kind: Secret
      metadata:
        name: ghcr-login-secret
        namespace: preview-hello-world-app
        labels:
          loft.sh/project-secret-name: ghcr-login-secret
      data:
        .dockerconfigjson: e30K
      type: kubernetes.io/dockerconfigjson
    access:
      rules:
        - teams:
            - loft-admins
          clusterRole: cluster-admin
    pro:
      enabled: true
    helmRelease:
      chart:
        version: 0.22.4
      values: |-
        external:
          platform:
            autoSleep:
              afterInactivity: 10800
              autoWakeup:
                schedule: 11 8-16 * * 1-5
            autoDelete:
              afterInactivity: 120000
        sync:
          toHost:
            ingresses:
              enabled: true
            secrets:
              all: true

        controlPlane:
          # Use an embedded managed etcd server instead of using the k3s default SQLite backend
          backingStore:
            etcd:
              embedded:
                enabled: true
          coredns:
            embedded: true
        policies:
          limitRange:
            enabled: true
          podSecurityStandard: baseline
          resourceQuota:
            enabled: true
    accessPoint:
      ingress: {}
    spaceTemplate:
      metadata: {}
  access:
    - verbs:
        - '*'
      subresources:
        - '*'
      users:
        - admin
---
apiVersion: management.loft.sh/v1
kind: VirtualClusterTemplate
metadata:
  name: sleepy-vcluster-template
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
spec:
  displayName: Sleepy vCluster Template
  description: This template deploys a sleepy virtual cluster
  template:
    metadata: {}
    instanceTemplate:
      metadata: {}
    pro:
      enabled: true
    helmRelease:
      chart:
        name: vcluster
        repo: https://loft-demos.github.io/vcluster-charts
        version: 0.22.4
      values: |
        sync:
          toHost:
            ingresses:
              enabled: true

        controlPlane:
          backingStore:
            etcd:
              embedded:
                enabled: true
          coredns:
            embedded: true
          statefulSet:
            image:
              repository: "loft-demos/vcluster-pro"
              tag: "0.22.4-k8s.{{ .Values.k8sVersion }}"
        
        external:
          platform:
            autoSleep:
              afterInactivity: {{ mul .Values.sleepAfter 60 }}
            autoDelete:
              afterInactivity: {{ mul .Values.sleepAfter 120 }}
    accessPoint:
      ingress: {}
    spaceTemplate:
      metadata: {}
  parameters:
    - variable: sleepAfter
      label: Sleep After Inactivity (minutes)
      type: number
      defaultValue: '2'
    - variable: k8sVersion
      label: k8sVersion
      description: Please select Kubernetes version
      options:
        - v1.32.2
        - v1.31.6
        - v1.30.10
        - v1.29.14
      defaultValue: v1.31.6
  access:
    - verbs:
        - get
      users:
        - '*'
