services:
  vind-local-domains:
    image: caddy:2.10.2
    restart: unless-stopped
    labels:
      dev.orbstack.domains: ${ARGOCD_HOST},${VCP_HOST},${FORGEJO_HOST},${INGRESS_WILDCARD_HOST}
      dev.orbstack.http-port: "80"
    environment:
      VCP_HOST: ${VCP_HOST}
      ARGOCD_HOST: ${ARGOCD_HOST}
      FORGEJO_HOST: ${FORGEJO_HOST}
      ARGOCD_UPSTREAM: ${ARGOCD_UPSTREAM}
      VCP_UPSTREAM: ${VCP_UPSTREAM}
      FORGEJO_UPSTREAM: ${FORGEJO_UPSTREAM}
      INGRESS_WILDCARD_HOST: ${INGRESS_WILDCARD_HOST}
      INGRESS_UPSTREAM: ${INGRESS_UPSTREAM}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      vind:
        aliases:
          - ${VCP_HOST}
          - ${ARGOCD_HOST}
          - ${FORGEJO_HOST}

networks:
  vind:
    external: true
    name: ${VIND_DOCKER_NETWORK}
