services:
  vind-local-domains:
    image: caddy:2.10.2
    restart: unless-stopped
    labels:
      dev.orbstack.domains: ${ARGOCD_HOST},${VCP_HOST},${FORGEJO_HOST}
    env_file:
      - .env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
