apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "vcp-gitops-pr"
  namespace: argocd
spec:
  generators:
    - pullRequest:
        gitea:
          owner: "vcluster-demos"
          repo: "vcp-gitops"
          api: "http://forgejo-http.forgejo.svc.cluster.local:3000"
          tokenRef:
            secretName: loft-demo-org-cred
            key: token
        requeueAfterSeconds: 30
  template:
    metadata:
      name: "vcp-gitops-{{branch}}-pr{{number}}"
    spec:
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        repoURL: "http://forgejo-http.forgejo.svc.cluster.local:3000/vcluster-demos/vcp-gitops.git"
        targetRevision: "{{head_sha}}"
        path: helm-chart/
        helm:
          parameters:
            - name: "image.repository"
              value: "forgejo.vcp.local/vcluster-demos/vcp-gitops/vcp-gitops-demo-app"
            - name: "image.tag"
              value: "{{head_short_sha}}"
            - name: "image.args.text"
              value: "Hello from vcp-gitops pr-{{number}} commit {{head_short_sha}}"
            - name: "ingress.hosts[0].host"
              value: "vcp-gitops-pr-{{number}}-vcp-gitops.vcp.local"
            - name: ingress.hosts[0].paths[0].backend.service.name
              value: juliet-app
            - name: ingress.hosts[0].paths[0].backend.service.port.name
              value: http
            - name: ingress.hosts[0].paths[0].path
              value: /
            - name: ingress.hosts[0].paths[0].pathType
              value: prefix
            - name: "ingress.tls[0].hosts[0]"
              value: "vcp-gitops-pr-{{number}}-vcp-gitops.vcp.local"
      project: "default"
      destination:
        server: "https://vcp-gitops.vcp.local/kubernetes/project/default/virtualcluster/vcp-gitops-pr-{{number}}"
        namespace: preview-hello-world-app
      info:
        - name: Preview App Link
          value: >-
            https://vcp-gitops-pr-{{number}}-vcp-gitops.vcp.local
        - name: Pull Request
          value: >-
            https://forgejo.vcp.local/vcluster-demos/vcp-gitops/pulls/{{number}}
