apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../flux-manifests.yaml
  - ../../flux-instance.yaml
  - ../../flux-pull-request-environments.yaml
patches:
  - path: patch-flux-manifests.yaml
  - path: patch-flux-pull-request-environments.yaml
  - path: patch-flux-instance.yaml
