apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flux-pull-request-environments
  namespace: argocd
spec:
  source:
    path: vcluster-use-cases/flux/pull-request-environments/overlays/local-contained
