apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kargo
  namespace: p-vcluster-flux-demo
spec:
  targetNamespace: kargo
  storageNamespace: kargo
  releaseName: kargo
  chart:
    spec:
      chart: kargo
      version: 1.9.5
      sourceRef:
        kind: HelmRepository
        name: kargo-charts
        namespace: p-vcluster-flux-demo
  interval: 50m
  driftDetection:
    mode: enabled
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    api:
      host: {REPLACE_KARGO_HOST}
      # Keep auth config out of Git. The referenced Secret is responsible for
      # setting api.adminAccount and/or api.oidc values.
      argocd:
        urls:
          "": "https://{REPLACE_ARGOCD_HOST}"
      tls:
        enabled: false
        terminatedUpstream: true
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
        tls:
          enabled: false
    externalWebhooksServer:
      host: {REPLACE_KARGO_WEBHOOK_HOST}
      logLevel: DEBUG
      tls:
        enabled: false
        terminatedUpstream: true
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
        tls:
          enabled: false
  valuesFrom:
    - kind: Secret
      name: kargo-auth-values
      valuesKey: values.yaml
      optional: false
