apiVersion: v1
kind: Secret
metadata:
  name: one-password-sa-token
  namespace: eso
  labels:
    loft.sh/project-secret-name: one-password-sa-token
type: Opaque
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vcp-demo-store
spec:
  provider:
    onepasswordSDK:
      vault: "Solution Architects"
      auth:
        serviceAccountSecretRef:
          name: one-password-sa-token
          namespace: eso
          key: token
      integrationInfo: # this is optional and defaulted
        name: vcp-demo-secrets
        version: v1
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loft-demos-ghcr-write
  namespace: p-default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vcp-demo-store
  target:
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: loft-demos-ghcr-write/username
    - secretKey: password
      remoteRef:
        key: loft-demos-ghcr-write/password