apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aws-ec2-node-provider-credentials
  namespace: vcluster-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vcp-demo-store
  target:
    name: aws-ec2-node-provider-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          terraform.vcluster.com/provider: aws-ec2-node-provider
      data:
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY:  "{{ .AWS_SECRET_ACCESS_KEY }}"
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: aws-ec2-node-provider-credentials/AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: aws-ec2-node-provider-credentials/AWS_SECRET_ACCESS_KEY