apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vcluster-env-config
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            env: dev
    - clusters:
        selector:
          matchLabels:
            env: qa
    - clusters:
        selector:
          matchLabels:
            env: prod
  template:
    metadata:
      name: {REPLACE_REPO_NAME}-{{.name}}
    spec:
      destination:
        namespace: {REPLACE_REPO_NAME}-{{.metadata.labels.env}}
        name: '{{.name}}'
      info:
        - name: Git Repo
          value: '{REPLACE_GIT_PUBLIC_URL}/{REPLACE_ORG_NAME}/{REPLACE_REPO_NAME}/'
      project: 'loft-{{ index .metadata.labels "demos.vcluster.com/project" }}'
      source:
        path: vcluster-use-cases/argocd-vcluster-add-ons/manifests/{{.metadata.labels.env}}/
        repoURL: '{REPLACE_GIT_BASE_URL}/{REPLACE_ORG_NAME}/{REPLACE_REPO_NAME}.git'
        targetRevision: '{REPLACE_GIT_TARGET_REVISION}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
