apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vcluster-env-config
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            env: dev
    - clusters:
        selector:
          matchLabels:
            env: qa
    - clusters:
        selector:
          matchLabels:
            env: prod
  template:
    metadata:
      name: vcp-gitops-{{.name}}
    spec:
      destination:
        namespace: vcp-gitops-{{.metadata.labels.env}}
        server: '{{.server}}'
      info:
        - name: Git Repo
          value: 'https://forgejo.vcp.local/vcluster-demos/vcp-gitops/'
      project: 'loft-{{ index .metadata.labels "demos.loft.sh/project" }}'
      source:
        path: vcluster-use-cases/argocd-vcluster-add-ons/manifests/{{.metadata.labels.env}}/
        repoURL: 'http://forgejo-http.forgejo.svc.cluster.local:3000/vcluster-demos/vcp-gitops.git'
        targetRevision: main
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
