apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: guestbook-shared-config
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: pre-prod-gate-shared-demo-store
  target:
    name: guestbook-shared-config
    creationPolicy: Owner
  data:
    - secretKey: message
      remoteRef:
        key: guestbook-shared-demo-source
        property: message
