name: delete-old-repo-package

# on the repository default branch
on:
  create:
  workflow_dispatch:
jobs:
  delete-old-repo-package:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == github.event.repository.default_branch }}
    steps:
      - id: delete-package
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.KM_PAT_DELETE_PACKAGES }}
        run: |
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /orgs/${{ github.repository_owner }}/packages/container/${{ github.event.repository.name }}
