name: replace-text

# on push to main
on:
  workflow_dispatch:
    inputs:
      vcluster_name:
        description: "Override default vCluster name which matches the repo name (minus `-app`)"
        required: false
        default: ""
      base_domain:
        description: "Base domain used to create example host names"
        required: true
        default: "us.demo.dev"
  push:
    branches:
      - main
    paths:
      - 'helm-chart/Chart.yaml'
env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  replace-text:
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      actions: write
    steps:
      - name: Set dynamic env vars with fallback
        run: |
          echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
          echo "ORG_NAME=${GITHUB_REPOSITORY_OWNER:-loft-demos}" >> $GITHUB_ENV
          BASE_DOMAIN="${{ github.event.inputs.base_domain }}"
          echo "BASE_DOMAIN=${BASE_DOMAIN:-us.demo.dev}" >> $GITHUB_ENV

      - name: set-vcluster-name
        run: |
          if [ -n "${{ inputs.vcluster_name }}" ]; then
            echo "VCLUSTER_NAME=${{ inputs.vcluster_name }}" >> "$GITHUB_ENV"
          else
            echo "VCLUSTER_NAME=$(echo "${REPO_NAME%-app}")" >> "$GITHUB_ENV"
          fi
          echo "vCluster name is $VCLUSTER_NAME"

      - uses: actions/checkout@v3

      - uses: flcdrg/replace-multiple-action@v2.0.148
        with:
          files: '**/*.yaml'
          find: '[{ "find": "{REPLACE_REPO_NAME}", "replace": "${{ env.REPO_NAME }}" }, \
                  { "find": "{REPLACE_ORG_NAME}", "replace": "${{ env.ORG_NAME }}" }, \
                  { "find": "{REPLACE_VCLUSTER_NAME}", "replace": "${{ env.VCLUSTER_NAME }}" }, \
                  { "find": "{REPLACE_BASE_DOMAIN}", "replace": "${{ env.BASE_DOMAIN }}" }]'
          prefix: ''
          suffix: ''

      - uses: stefanzweifel/git-auto-commit-action@v5

      - name: delete-package
        env:
          GITHUB_TOKEN: ${{ secrets.KM_PAT_DELETE_PACKAGES }}
        run: |
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /orgs/${{ env.ORG_NAME }}/packages/container/${{ env.REPO_NAME }}

      - name: Disable this workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow disable -R $GITHUB_REPOSITORY "${{ github.workflow }}"